In [1]:
import pandas as pd
import numpy as np
df = pd.read_excel(r"C:\Users\Admin\Desktop\sem 5\ML\ML lab\Lab Session1 Data.xlsx",sheet_name='Purchase data')
df = df.dropna(axis=1)
print(df)
A = df[['Candies (#)', 'Mangoes (Kg)', 'Milk Packets (#)']].values
C = df[['Payment (Rs)']].values
print("Matrix A")
print(A)
print("Matrix C")
print(C)
Au = np.hstack((A, C))
print("Agumented Matrix of A and C")
print(Au)
d=np.linalg.matrix_rank(Au)
print("Dimensionality of the Vector Space")
print(d)
R_A=np.linalg.matrix_rank(A)
print("Rank of Matrix A")
print(R_A)
Ain=np.linalg.pinv(A)
print("Pseudo inverse of matrix A")
print(Ain)
X=np.matmul(Ain,C)
print("Matrix X")
print(X)

  Customer  Candies (#)  Mangoes (Kg)  Milk Packets (#)  Payment (Rs)
0      C_1           20             6                 2           386
1      C_2           16             3                 6           289
2      C_3           27             6                 2           393
3      C_4           19             1                 2           110
4      C_5           24             4                 2           280
5      C_6           22             1                 5           167
6      C_7           15             4                 2           271
7      C_8           18             4                 2           274
8      C_9           21             1                 4           148
9     C_10           16             2                 4           198
Matrix A
[[20  6  2]
 [16  3  6]
 [27  6  2]
 [19  1  2]
 [24  4  2]
 [22  1  5]
 [15  4  2]
 [18  4  2]
 [21  1  4]
 [16  2  4]]
Matrix C
[[386]
 [289]
 [393]
 [110]
 [280]
 [167]
 [271]
 [274]
 [148]
 [198]]
Agumented Matrix of 